class Reader:
    def __init__(self, path: str) -> None: ...
    @property
    def size(self) -> int: ...
    @property
    def frame_count(self) -> int: ...
    def read_range(self, start: int, end: int) -> bytes: ...
    def read_ranges(self, ranges: list[tuple[int, int]]) -> list[bytes]: ...
    def __enter__(self) -> "Reader": ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> bool: ...
