/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class Reader {
  constructor(path: string)
  get size(): number
  get frameCount(): number
  readRange(start: number, end: number): Buffer
  readRangeAsync(start: number, end: number): Promise<Buffer>
  /**
   * Closes the reader and releases resources.
   * After calling close(), any further operations will throw an error.
   */
  close(): void
}
